import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
// import styles from './page.module.css'
// import illustration from "./https://seadn.weknowcreators.xyz/media/content/hero-illustration.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Password Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/safety-svgrepo-com.png" />
      </Head>
    </>
  );
}
