import Head from "next/head";
// import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* start nav bar */}
      <div className="navbar bg-base-100">
        <a className="btn btn-ghost normal-case text-xl">Password Generator</a>
      </div>
      {/* special char selection */}
      <select className="select select-info w-full max-w-xs">
        <option disabled defaultValue>
          Exclude Special Characters
        </option>
        <option>True</option>
        <option>False</option>
      </select>
      {/* Pass length */}
      <div>
        <input
          type="number"
          placeholder="Pass length"
          className="input input-bordered input-info w-full max-w-xs"
        />
      </div>
      {/* Exclude Numbers selection */}
      <select className="select select-info w-full max-w-xs">
        <option disabled defaultValue>
          Exclude Numbers
        </option>
        <option>True</option>
        <option>False</option>
      </select>
      <br />
      <br />
      <button className="btn btn-outline btn-info">Generate</button>
      <br />
      <br />
      {/* password generated */}
      <div className="mockup-code">
        <pre data-prefix="$">
          <code>pass</code>
        </pre>
      </div>
    </>
  );
}
